### ISSUE TITLE
Semi-verbose output option

### ISSUE THREAD

**Issue by ericonr** [brunoseivam/retools#3]
Hi! This is an awesome module, I was about to look into programmatically generating db files with alias definitions, which would have to be kept up to date, when I remembered I had come across your repo :)

Since I have a lot of aliases, reAddAlias output is quite verbose, but simply disabling verbose output for retools feels like it's lacking feedback. Would you be interested in an output option for reAddAlias which simply outputs the number of aliases that it created due to the command? I could implement it, but figured I should ask before putting time into it.

(btw, since you're using c++11 regexes and not introducing new complicated dependencies, do you think there's a chance this module could ever become official? are you interested in pursuing that?)

**Comment by brunoseivam** [comment]
Hey, thanks! Feel free to open a PR, I'd be happy to merge it.

Yeah, I don't know what you mean by official :) I can transfer this into epics-modules, I don't know who is taking care of it these days. I'd have to check if there would be interest in merging this into base, but it would depend on them moving to C++11, I am not sure if that ended up happening.

**Comment by ericonr** [comment]
Great :)

Yeah, I guess I meant either transferring to the epics-modules org or merging to base. Most CI runs seem to be using gcc-9+, which seems positive. But the CentOS 7 one is using `gcc-c++.x86_64 0:4.8.5-44.el7`, and non-experimental C++11 support came out with GCC 5.1.

**Comment by nariox** [comment]
Hey Érico,
I have worked on something addressing this issue (not the GCC one, I vouched never to maintain GCC packaging again back in 2015, haha). See if this is somewhat what you are looking for.

I chose to use `2` as the option to maintain compatibility with older versions. I am considering adding `3` as an option to show both the old verbose output and the new total message. I'd appreciate your input on it.

**Comment by ericonr** [comment]
It seems to be, thank you very much! I like the bitmask idea, but we'd have to see @brunoseivam's opinion about it.

I left some review comments on your PR too :)

**Comment by brunoseivam** [comment]
Treating it as a bitmask is a good idea, similar to what asyn does. I don't feel strongly either way. If you can propose a good bitmask approach that's hopefully backwards compatible, I would merge it. Thanks!

**Comment by brunoseivam** [comment]
Closed via #4

**Comment by nariox** [comment]
Esses BR são bão! Valeu Bruno e Érico!
